
      

        <header class="wrapper classement-wrapper" id="test">
            <div class="classement-max-back">
                <div id="classement-back"></div>
            </div>
            <div class="navigation-principal">
                <div class="logo-nav">
                    <div id="logo-nav">
                        <a href="index.php"><img src="views\img\logo-tt-color.png" alt="Logo as mornant"></a>
                        <i class="fa-solid test"></i>
                    </div>
                </div>
                <nav class="nav-bar" id="nav">
                    <ul class="sous">
                        <li ><a href="index.php" >Accueil</a></li>
                        <li ><a href="javascript:void(0)" class="icon club color-white">Le club</a>
                            <ul class="sous-menu2 club1">
                                <li><a href="#">Historique</a></li>
                                <li><a href="index.php?action=inscription">Inscription</a></li>
                                <li><a href="index.php?action=contact">Nous contacter</a></li>
                            </ul>
                        </li>
                        <li><a href="javascript:void(0)" class="icon competitions color-white">Les compétitions</a>
                            <ul class="sous-menu2 competitions1">
                                <li><a href="#">Equipe 1</a></li>
                                <li><a href="#">Equipe 2</a></li>
                                <li><a href="#">Equipe 3</a></li>
                                <li><a href="#">Equipe 4</a></li>
                                <li><a href="#">Equipe 5</a></li>
                                <li><a href="#">Equipe 6</a></li>
                                <li><a href="#">Equipe 7</a></li>
                            </ul>
                        </li>
                        <li><a href="#" class="color-white current">Classement joueurs</a></li>
                    </ul>
                </nav>
                
            </div>
                <div class="entrnmt-text-header">
                    
                    <h1>Classement des joueurs</h1>
                    
                </div>
            </header>

    <main class="container historique-container">
        <!-- Afficher la liste des joueurs
        echo "Licence: $joueur->licence, Nom: $joueur->nom, Prénom: $joueur->prenom, Numéro du Club: $joueur->nclub, Classement: $joueur->clast\n"; -->
        <section class="">
            
            <div class="bar-search-classement">
                <div class="search-classement">
                    <i class="fa-solid fa-magnifying-glass"></i>
                    <input type="text" id="search" placeholder="Rechercher..">
                </div>
                <div class="trie-classement">   
                    <form method="GET" action="" id="triForm">
                        <select name="mode" id="tri">
                            <option value="nom" <?php if ($modeDeTri === 'nom') echo 'selected'; ?>>Trier par nom</option>
                            <option value="point" <?php if ($modeDeTri === 'point') echo 'selected'; ?>>Trier par point</option>
                            <option value="pointm" <?php if ($modeDeTri === 'pointm') echo 'selected'; ?>>Trier par point mensuel</option>
                        </select>
                    </form>
                </div>
            </div>
            <div class="section-classement">
                <div class="back-entete-tableau-classement">

                
                    <div class="entete-tableau-classement">
                        <h3 class="entete-nom">Nom Prenom</h3>
                        <h3>N°Licence</h3>
                        <h3>Point officiels</h3>
                        <h3>Évolution</h3>
                        <h3>Point mensuel</h3>
                        
                    </div>
                </div>
                    <table class="tableau-classement">
                        <tbody class="body-tableau-classement" id="search-results">
                            <?php foreach ($data as $licence) { ?> 
                                <tr>
                                    
                                    <td style="font-weight: bold"><?php echo $licence->nom . ' ' . $licence->prenom ?></td>
                                    <td><?php echo $licence->licence ?></td>
                                    <td><?php echo $licence->point ?></td>
                                    <td class="logo-classement">
                                        <?php
                                        $point = intval($licence->point);
                                        $pointm = intval($licence->pointm);
                                        if ($point < $pointm) {
                                            echo "Progression <i class='fa-solid fa-angles-up'></i>";
                                        } elseif ($point == $pointm + 1 || $point == $pointm || $pointm == '0') {
                                            echo "Stable <i class='fa-solid fa-equals'></i>";
                                        } elseif ($point > $pointm ) {
                                            echo "Baisse <i class='fa-solid fa-angles-down'></i>";
                                        }
                                        ?>
                                    </td>
                                    <td>
                                        <?php 
                                        $arondi = intval($licence->pointm);
                                        echo round($arondi) 
                                        ?>
                                    </td>
                                    
                                </tr>
                                <?php } ?>
                        </tbody>
                    </table>
                </div>
            <div>
            
            
        
        </section>
    </main>
    <!-- script de recherche liste classement -->
    <script>
     $(document).ready(function(){
        $('#search').keyup(function(){
            var query = $(this).val().toLowerCase();
            $(".body-tableau-classement tr").filter(function() {
                $(this).toggle($(this).text().toLowerCase().indexOf(query) > -1)
            });
        });
    });

    document.getElementById('tri').addEventListener('change', function() {
        var mode = this.value;
        var currentUrl = window.location.href;
        var url = new URL(currentUrl);
        var params = new URLSearchParams(url.search);
        params.set('mode', mode);
        window.location.href = url.pathname + '?' + params.toString();
    });
    

    </script>
            
    