
      

        <header class="wrapper contact-wrapper" id="test">
            <div class="contact-max-back">
                <div id="contact-back"></div>
            </div>
            <div class="navigation-principal">
                <div class="logo-nav">
                    <div id="logo-nav">
                        <a href="index.php"><img src="views\img\logo-tt-color.png" alt="Logo as mornant"></a>
                        <i class="fa-solid test"></i>
                    </div>
                </div>
                <nav class="nav-bar" id="nav">
                    <ul class="sous">
                        <li ><a href="index.php">Accueil</a></li>
                        <li ><a href="javascript:void(0)" class="icon club color-white current">Le club</a>
                            <ul class="sous-menu2 club1">
                                <li><a href="index.php?action=historique">Historique</a></li>
                                <li><a href="index.php?action=inscription">Inscription</a></li>
                                <li><a href="#">Nous contacter</a></li>
                            </ul>
                        </li>
                        <li><a href="javascript:void(0)" class="icon competitions color-white">Les compétitions</a>
                            <ul class="sous-menu2 competitions1">
                                <li><a href="#">Equipe 1</a></li>
                                <li><a href="#">Equipe 2</a></li>
                                <li><a href="#">Equipe 3</a></li>
                                <li><a href="#">Equipe 4</a></li>
                                <li><a href="#">Equipe 5</a></li>
                                <li><a href="#">Jeune</a></li>
                                <li><a href="#">Tournois</a></li>
                            </ul>
                        </li>
                        <li><a href="#" class="color-white">Classement joueurs</a></li>
                    </ul>
                </nav>
                
            </div>
                <div class="entrnmt-text-header">
                    
                    <h1>Nous contacter</h1>
                    
                </div>
            </header>
            <main class="container contact-container">

                <section class="contact">
                    <article class="contact-gymnase">

                        
                        <div class="contact-adresse">
                            <img src="views/img/gymnase.png" alt="gymnase de la tannerie Mornant">
                            <div class="contact-text">

                                <h2>Contact</h2>
                                <address>
                                    <p>Gymnase de la Tannerie</p>
                                    <p>10 Rte de Saint-Sorlin,</p>
                                    <p>69440 Mornant</p>
                                    <p>Tel : 202058858</p>
                                    <p>emailmelmlrer@gmail.com</p>
                                </address>
                            </div>
                        </div>

                        
                        
                    </article>
                    <article class="contact-google">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d6637.117842003577!2d4.667144584805354!3d45.61939904345314!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47f4fb2825e54c4f%3A0x5c6e5773aa1103ce!2sGymnase%20de%20la%20Tannerie!5e0!3m2!1sfr!2sfr!4v1687773803627!5m2!1sfr!2sfr" width="100%" height="500" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                    </article>

                    <article class="contact-formulaire">

                        <form action="formulaire.php" method="post">
                            <h2>envoyer un message</h2>
                            <label for="nom">Nom</label>
                            <input type="text" name="nom" placeholder="Votre nom" required>
                            <label for="email">Email</label>
                            <input type="email" name="email" placeholder="votreemail@email.com" required>
                            <label for="tel">Téléphone</label>
                            <input type="tel" name="tel" placeholder="Votre numéro de téléphone" required>
                            <label for="sujet">Sujet</label>
                            <input type="text" name="sujet" placeholder="A propos.." required>
                            <label for="message">Message</label>
                            <textarea name="message" id=""placeholder="Bonjour..." required></textarea>
                            <button type="submit">Envoyer</button>
                            
                        </form>
                    </article>
                </section>



            </main>
            