
      

        <header class="wrapper classement-wrapper" id="test">
            <div class="classement-max-back">
                <div id="classement-back"></div>
            </div>
            <div class="navigation-principal">
                <div class="logo-nav">
                    <div id="logo-nav">
                        <a href="index.php"><img src="views\img\logo-tt-color.png" alt="Logo as mornant"></a>
                        <i class="fa-solid test"></i>
                    </div>
                </div>
                <nav class="nav-bar" id="nav">
                    <ul class="sous">
                        <li ><a href="index.php" >Accueil</a></li>
                        <li ><a href="javascript:void(0)" class="icon club color-white">Le club</a>
                            <ul class="sous-menu2 club1">
                                <li><a href="#">Historique</a></li>
                                <li><a href="index.php?action=inscription">Inscription</a></li>
                                <li><a href="index.php?action=contact">Nous contacter</a></li>
                            </ul>
                        </li>
                        <li><a href="javascript:void(0)" class="icon competitions color-white  current">Les compétitions</a>
                            <ul class="sous-menu2 competitions1">
                                <li><a href="index.php?action=equipe1" class=" current">Equipe 1</a></li>
                                <li><a href="index.php?action=equipe2">Equipe 2</a></li>
                                <li><a href="index.php?action=equipe3">Equipe 3</a></li>
                                <li><a href="index.php?action=equipe4">Equipe 4</a></li>
                                <li><a href="index.php?action=equipe5">Equipe 5</a></li>
                                <li><a href="index.php?action=equipe6">Equipe 6</a></li>
                                <li><a href="index.php?action=equipe7">Equipe 7</a></li>
                            </ul>
                        </li>
                        <li><a href="index.php?action=classement" class="color-white">Classement joueurs</a></li>
                    </ul>
                </nav>
                
            </div>
                <div class="entrnmt-text-header">
                    
                    <h1>Equipe 1</h1>
                    
                </div>
            </header>

    <main class="container historique-container">
       
        <section class="">
            
            
            <?php foreach ($equipeData as $equipe) { ?>

            <p><?php echo $equipe->libequipe ?> </p>
            <p><?php echo $equipe->libdivision ?> </p>
            <p><?php echo $equipe->liendivision ?> </p>
            <p><?php echo $equipe->idepr ?> </p>
            <p><?php echo $equipe->libepr ?> </p>
            </br>
            </br>


            <?php } ?>

            <?php foreach ($pouleClassement as $class) { ?>
                <table style="width: 90%;">
                    <thead>
                        <tr>
                            <th>Pos</th>
                            <th>equipe</th>
                            <th>Pts</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><?php echo $class->clt ?></td>
                            <td><?php echo $class->equipe ?></td>
                            <td><?php echo $class->pts ?></td>
                        </tr>
                    </tbody>
                </table>
                <h2></h2>
                <h2></h2>
                <h2></h2>
            <?php } ?>
            
        
        </section>
    </main>
            
    