
      

        <header class="wrapper historique-wrapper" id="test">
            <div class="historique-max-back">
                <div id="historique-back"></div>
            </div>
            <div class="navigation-principal">
                <div class="logo-nav">
                    <div id="logo-nav">
                        <a href="index.php"><img src="views\img\logo-tt-color.png" alt="Logo as mornant"></a>
                        <i class="fa-solid test"></i>
                    </div>
                </div>
                <nav class="nav-bar" id="nav">
                    <ul class="sous">
                        <li ><a href="index.php" >Accueil</a></li>
                        <li ><a href="javascript:void(0)" class="icon club color-white current">Le club</a>
                            <ul class="sous-menu2 club1">
                                <li><a href="#">Historique</a></li>
                                <li><a href="index.php?action=inscription">Inscription</a></li>
                                <li><a href="index.php?action=contact">Nous contacter</a></li>
                            </ul>
                        </li>
                        <li><a href="javascript:void(0)" class="icon competitions color-white">Les compétitions</a>
                            <ul class="sous-menu2 competitions1">
                                <li><a href="#">Equipe 1</a></li>
                                <li><a href="#">Equipe 2</a></li>
                                <li><a href="#">Equipe 3</a></li>
                                <li><a href="#">Equipe 4</a></li>
                                <li><a href="#">Equipe 5</a></li>
                                <li><a href="#">Jeune</a></li>
                                <li><a href="#">Tournois</a></li>
                            </ul>
                        </li>
                        <li><a href="#" class="color-white">Classement joueurs</a></li>
                    </ul>
                </nav>
                
            </div>
                <div class="entrnmt-text-header">
                    
                    <h1>Historique du club</h1>
                    
                </div>
            </header>

    <main class="container historique-container">
        <section class="historique-section">

            <article class="">
                
                <img src="views/img/aaaa001.jpg" alt="photo extrait d'un journal"  class="img-modal historique-left">
                <div class="historique-text">

                    <h2>Une nouvelle activité..</h2>
                    <p>En avril 1989 à l'initiative de Martine et Jacques FUCHY et de René GOUILLON après avoir pratiqué la compétition à Chassagny puis à St Andéol se crée une section Tennis de Table au sein de l'AS MORNANT (association multisports qui à l'époque comprenait également le foot, le basket, le hand et le volley).</p>
                </div>
                
            </article>
            <article>
                
                <img src="views/img/aaaa003.jpg" alt="photo extrait d'un journal" class="img-modal">
                <div class="historique-text2">

                    <p>Dans les années 90 suite à l'éclatement de l'ASM chaque section crée son association autonome.</p>
                    
                    <p>   Le Club s'est toujours attaché à la formation en initiant de nombreux jeunes à la pratique du Tennis de Table au début avec des adhérents bénévoles puis depuis de nombreuses années avec un entraîneur diplômé salarié.</p>
                </div>
                
                <img src="views/img/aaaa004.jpg" alt="photo extrait d'un journal" class="img-modal">
                <div class="historique-text3">

                    <p> La politique tarifaire a toujours été de pratiquer un tarif abordable pour les familles. </p>
                </div>
                    
        </article>
        <article>
            <img src="views/img/aaaa005.jpg" alt="photo extrait d'un journal" class="img-modal">
            <div class="historique-text4">

                <p>Au fil des années grâce aux efforts de formation de jeunes et au renfort de joueurs locaux pratiquant jusqu'alors dans d'autres clubs l'ASMTT inscrit en championnat départemental FFTT jusqu'à 4 équipes soit seize joueurs.</p>
                
                <p>L'équipe première fait plusieurs fois la navette entre départementale 1 et pré régionale sans jamais atteindre le niveau régional.</p>
            </div>
            
            
        </article>
        <article class="historique-presidence">
            <h3>A la présidence se sont succédés :</h3>
            <ul>

                <li>De 1990 à 2002 <strong>Jacques FUCHY</strong> </li>
                <li>De 2003 à 2009 <strong>Lionel RICHER</strong></li>
                <li>De 2009 à 2014 <strong>Joel CHAGNEAUD</strong> </li>
                <li>Depuis 2015 <strong>Jacques FUCHY</strong> </li>
            </ul>
        </article>

        <article class="historique-association">
            <p>Association loi 1901</p>
            <p>Siége Mairie de Mornant</p>
            <p>Numéro de récipissé Préfecture : W691088041</p>
            <p>Numéro de Siret : 445 365 679 000 15</p>
            <p>Numéro Agrément Jeunesse et Sport : 69031203</p>
            <p>Numéro affiliation club FFTT : 01690167</p>
        </article>
        <div id="myModal" class="modal-photo">
            <!-- The Close Button -->
            <span class="close-photo">&times;</span>
            
            <!-- Modal Content (The Image) -->
            <div class="slider-container">
                <img id="img01" alt="" style="width: 100%;">
                <!-- Les images du slider seront ajoutées dynamiquement ici -->
            </div>
            
            
            <!-- Modal Caption (Image Text) -->
            <!-- <div id="caption"></div> -->
        </div>
    </section>

    </main>
                            
    