
        <header class="wrapper" id="test">
            <div class="max-back">
                <div id="back"></div>
            </div>
            <div class="navigation-principal">
                <div class="logo-nav">
                    <div id="logo-nav">
                        <a href="#"><img src="views\img\logo-tt-color.png" alt="Logo as mornant"></a>
                        <i class="fa-solid test"></i>
                    </div>
                </div>
                <nav class="nav-bar" id="nav">
                    <ul class="sous">
                        <li ><a href="#" class="current">Accueil</a></li>
                        <li ><a href="javascript:void(0)" class="icon club color-white">Le club</a>
                            <ul class="sous-menu2 club1">
                                <li><a href="index.php?action=historique">Historique</a></li>
                                <li><a href="index.php?action=inscription">Inscription</a></li>
                                <li><a href="index.php?action=contact">Nous contacter</a></li>
                            </ul>
                        </li>
                        <li><a href="javascript:void(0)" class="icon competitions color-white">Les compétitions</a>
                            <ul class="sous-menu2 competitions1">
                                <li><a href="#">Equipe 1</a></li>
                                <li><a href="#">Equipe 2</a></li>
                                <li><a href="#">Equipe 3</a></li>
                                <li><a href="#">Equipe 4</a></li>
                                <li><a href="#">Equipe 5</a></li>
                                <li><a href="#">Jeune</a></li>
                                <li><a href="#">Tournois</a></li>
                            </ul>
                        </li>
                        <li><a href="#" class="color-white">Classement joueurs</a></li>
                    </ul>
                </nav>
                
            </div>
            <div class="text-header">
                <div>
                    
                    <h1>Bienvenue sur le site de l'<strong>AS MORNANT</strong></h1>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque praesentium recusandae
                        necessitatibus nisi velit iu, aperiam cumque officia mnima!</p>
                    </div>
                    <div class="header-lien">
                        <a href="#infos">Dernières infos</a>
                        <a href="calendrier.html" class="header-calendrier">Calendrier 2023/2024</a>
                    </div>
                </div>
            </header>

    <main class="container">
        <div class="fond-ourtennisclub">
            
            <div class="ourtennisclub">
                <p>Nous rejoindre.</p>
                <h2>Our table tennis club offers</h2>
                <p>Si vous souhaitez rejoindre le Club de Tennis de Table de Mornant, n'hésitez pas à venir nous
                    rencontrer ! Le mercredi de 19h30 à 21h30 et le vendredi de 19h à 21h !</p>
                    <p>Les raisons de nous rejoindre sont nombreuses :</p>
                </div>
                
                <section class="section-ourclub">
                    <article>
                        <div class="animation-1">
                            <img src="views/img/entraineur.png" alt="tennis-table">
                        </div>
                        <h3>Apprentissage</h3>
                        <p>Apprendre à jouer au tenis de table, se remettre à ce sport après quelques années sans jouer,
                            venir échanger des balles en formule Loisir</p>
                        </article>
                        <article>
                            <div class="animation-2">
                                <img src="views/img/entraineur.png" alt="tennis-table">
                            </div>
                            <h3>Entrainement</h3>
                            <p>Pouvoir disposer des conseils d'un entraineur confirmé au cours d'entrainements dirigés</p>
                        </article>
                        
                        <article>
                            <div class="animation-1">
                                <img src="views/img/garcon.jpg" alt="tennis-table">
                            </div>
                            <h3>Convivialité</h3>
                            <p>Profiter d'un réel esprit de convivialité, mêlant jeunes pratiquants et adultes de tout âge</p>
                        </article>
                        <article>
                            <div class="animation-2">
                                <img src="views/img/salle.jpg" alt="tennis-table">
                            </div>
                            <h3>Compétition</h3>
                            <p>Avoir la possibilité de jouer en compétition par équipe</p>
                        </article>
                        <div class="boutton-inscription">
                            
                            <h3>Nous vous attendons nombreux !</h3>
                            
                            <a href="index.php?action=inscription">Modalités d'inscription</a>
                        </div>
                    </section>
                </div>
                <hr id="infos">
                <section class="section-nouveaute">
                    <h2>Dernières infos</h2>
                    <article class="animation-droite nouveaute-article" data-article-id="article3">
                        <div class="slider">
                            <div><img src="views/img/photo-groupe-derniere-journee.jpg" alt="Photo groupe" class="img-modal" id="imgmodal"></div>
                            <div><img src="views/img/photo-groupe-derniere-journee.jpg" alt="Photo groupe" class="img-modal" id="imgmodal"></div>
                        </div>
                        <div class="nouveaute">
                            <div class="logo-raquette-nouveaute">
                                <img src="views/img/raq-tt-color.png" alt="logo-raquette">
                            </div>
                            <h3>Dernière journée du championnat WE par équipe Phase 2</h3>
                            <date>Dimanche 14 mai 2023</date>
                            <p><strong>Voici le bilan des équipes à l'issue de cette 7ème journée :</strong></p>
                            <ul>
                                <li><strong>Équipe 1 en PR</strong> : Un bilan exceptionnel. La 1ère place de la poule et la montée en R3. BRAVO !!</li>
                                <li><strong>Équipe 2 en D1</strong> :  3 victoires et 4 défaites. Une belle équipe solide. Le maintien est assuré en D1</li>
                                <li><strong>Équipe 3 en D2</strong> : 3 victoires et 4 défaites. Maintien assuré pour l'équipe des pingouins</li>
                                <li><strong>Équipe 4 en D2</strong> : une victoire et 5 défaites. Maintien en D2 pour cette équipe</li>
                                <li><strong>Équipe 5 en D3</strong> : 4 victoires et 3 défaites. Un très bon bilan en D3. Plusieurs joueurs ont participé à la compétition pour la première fois. De belles perspectives pour la saison 2022-2023</li>
                            </ul>
                            <a href="#" class="lien-classement">Classements des joueurs</a>
                        </div>
                    </article>
                    <article class="animation-gauche  nouveaute-article" data-article-id="article1">
                        <div class="slider">
                            <div><img src="views/img/tournoi-jeune2.jpg" alt="photo tournoi-jeune2" class="img-modal"></div>
                            <div><img src="views/img/tournoi-jeune1.jpg" alt="photo tournoi-jeune1" class="img-modal"></div>
                        </div>
                        <div class="nouveaute text-jeune">
                            <div class="logo-raquette-nouveaute">
                                <img src="views/img/raq-tt-color2.png" alt="logo-raquette" >
                            </div>
                            <h3>Tournoi jeunes du Club</h3>
                            <!-- <date>11 mars 2023</date> -->
                            <p>Le tournoi jeunes du Club s'est déroulé le 11 mars 2023. Un très bon moment apprécié des
                                jeunes...</p>
                                <button type="button" id="open">Voir la suite..</button>
                            </div>
                            <div class="overlay"></div>
                            <div class="modal">
                                <div class="container-modal">

                                    <h3>Le tournoi jeunes s'est déroulé le samedi 11 mars 2023 à Mornant</h3>
                                    <p>32 jeunes ont participé dont une douzaine de Mornant. Les clubs représentés ont été les suivants
                                        : Lyon 6, Mions, Rhône-Garon, Messimy et Orliénas.</p>
                                        <ul>
                                            <li> <strong>Merci aux présents</strong> pour leur participation à l'installation, à la gestion
                                                de la buvette et au rangement </li>
                                                <li> <strong>Merci et bravo à Dominique</strong> qui a dirigé le tournoi de main de maître </li>
                                                <li> <strong>Merci particulièrement à la maman de Lenny Viollet</strong> qui a réussi à trouver
                                                    de jolis lots au dernier moment </li>
                                                    <li> <strong>Merci enfin à Cédric Belmont</strong> qui a fabriqué en découpe laser des
                                                        porte-clés et des trophées superbes en plexiglas </li>
                                                    </ul>
                                                    <button type="button" id="close">Fermer</button>
                                                </div>
                                            </div>
                                        </article>
                                        <article class="animation-droite">
                                            <div class="slider">
                                                <div><img src="views/img/Soiree-choucroute3.jpg" alt="photo soiree choucroute" class="img-modal"></div>
                                                <div><img src="views/img/Soiree-choucroute1.jpg" alt="photo soiree choucroute" class="img-modal"></div>
                                                <div><img src="views/img/Soiree-choucroute2.jpg" alt="photo soiree choucroute" class="img-modal"></div>
                                            </div>
                                            <div class="nouveaute">
                                                <div class="logo-raquette-nouveaute">
                                                    <img src="views/img/raq-tt-color.png" alt="logo-raquette">
                                                </div>
                                                <h3>Soirée choucroute</h3>
                                                <date>25 mars 2023</date>
                                        <p>L'AS Mornant TT et l'amicale Boule Mornantaise ont organisé ensemble une soirée choucroute</p>
                                        <p>Plus de 200 personnes ont répondu présent. Une belle soirée pour les 2 associations mornantaises
                                        </p>
                                    </div>
                                </article>
                                <article class="animation-gauche  nouveaute-article" data-article-id="article2">
                                    <div class="slider">
                                        <div><img src="views/img/maillot.jpg" alt="photo maillot" class="img-modal"></div>
                                        <div><img src="views/img/short.jpg" alt="photo short" class="img-modal"></div>
                                    </div>
                                    <div class="nouveaute">
                                        <div class="logo-raquette-nouveaute">
                                            <img src="views/img/raq-tt-color2.png" alt="logo-raquette">
                                        </div>
                                        <h3>NOUVELLE TENUE</h3>
                                        <p>La nouvelle tenue de l'AS MORNANT TT est arrivée.
                                            Merci Cédric</p>
                                        </div>
                                    </article>
                                    <div id="myModal" class="modal-photo">
                                        <!-- The Close Button -->
                                        <span class="close-photo">&times;</span>
                                        
                                        <!-- Modal Content (The Image) -->
                                        <div class="slider-container">
                                            <img id="img01" alt="">
                                            <!-- Les images du slider seront ajoutées dynamiquement ici -->
                                        </div>
                                        
                                        
                                        <!-- Modal Caption (Image Text) -->
                                        <!-- <div id="caption"></div> -->
                                    </div>
                                </section>
                                
                                
                                
                            </main>
                            
                            