

        <header class="wrapper inscription-wrapper" id="test">
            <div class="inscription-max-back">
                <div id="inscription-back"></div>
            </div>
            <div class="navigation-principal">
                <div class="logo-nav">
                    <div id="logo-nav">
                        <a href="index.php"><img src="views\img\logo-tt-color.png" alt="Logo as mornant"></a>
                        <i class="fa-solid test"></i>
                    </div>
                </div>
                <nav class="nav-bar" id="nav">
                    <ul class="sous">
                        <li ><a href="index.php" >Accueil</a></li>
                        <li ><a href="javascript:void(0)" class="icon club color-white current">Le club</a>
                            <ul class="sous-menu2 club1">
                                <li><a href="index.php?action=historique">Historique</a></li>
                                <li><a href="#">Inscription</a></li>
                                <li><a href="index.php?action=contact">Nous contacter</a></li>
                            </ul>
                        </li>
                        <li><a href="javascript:void(0)" class="icon competitions color-white">Les compétitions</a>
                            <ul class="sous-menu2 competitions1">
                                <li><a href="#">Equipe 1</a></li>
                                <li><a href="#">Equipe 2</a></li>
                                <li><a href="#">Equipe 3</a></li>
                                <li><a href="#">Equipe 4</a></li>
                                <li><a href="#">Equipe 5</a></li>
                                <li><a href="#">Jeune</a></li>
                                <li><a href="#">Tournois</a></li>
                            </ul>
                        </li>
                        <li><a href="#" class="color-white">Classement joueurs</a></li>
                    </ul>
                </nav>
                
            </div>
                <div class="entrnmt-text-header">
                    
                    <h1>Inscription</h1>
                    
                </div>
            </header>

            <main class="container inscription-container">

                <section class="inscription">
                    <div class="inscription-slider">
                        <div>

                            <article class="inscription-ajustement1" id="inscription-slide">
                                <p>SAISON 2022-2023</p>
                                <img src="views/img/family.png" alt="logo famille">
                                <h2> Adulte Loisir </h2>
                                <div class="inscription-text">
                                    
                                    <p>Le mercredi de 19h30 à 21h30.</p>
                                    <p>Le vendredi de 19h à 21h.</p>
                                </div>
                                
                                <h3>120<sup>€</sup></h3>
                                
                                <a href="#inscription-dossier1" id="inscription-dossier1" >Dossier d'inscription</a>
                                
                                
                                
                                
                            </article>
                            <div class="inscription-modal" id="inscription-modal">
                                <div class="inscription-container-modal">
                                    <h2>Dossier d'inscription Loisir</h2>
                                    <div>

                                        <a href="views/fichier/1-demande-de-licence-2022.pdf" target="_blank"><img src="views/img/1-demande-de-licence-2022-pdf.png" alt="logo formulaire licence" width="65px"></a>
                                        <a href="views/fichier/1-demande-de-licence-2022.pdf" target="_blank"><h3>Licence 2022/2023 <i class="fa-solid fa-download"></i></h3></a>
                                    </div>
                                    <div>

                                        <a href="views/fichier/2-certificat-medical-2022.pdf" target="_blank"><img src="views/img/logo_certicat_medical.png" alt="logo certificat medical" width="65px"></a>
                                        <a href="views/fichier/2-certificat-medical-2022.pdf" target="_blank"><h3>Certificat medical <i class="fa-solid fa-download"></i></h3></a>
                                        <p>(de moins de 3 mois)</p>
                                        <p>Pour les licenciés actuels, le certificat medical est valide 3 ans à condition de compléter le questionnaire sante</p>
                                    </div>
                                    <div>

                                        <a href="views/fichier/5-droit-image-2022-2023 (1).pdf" target="_blank"><img src="views/img/camera-g06822f641_640.png" alt="logo camera" width="70px"></a>
                                        <a href="views/fichier/5-droit-image-2022-2023 (1).pdf" target="_blank"><h3>Formulaire de droit a l'image <i class="fa-solid fa-download"></i></h3></a>
                                        <p>Pour les nouveaux adhérents uniquement</p>
                                    </div>
                                    <div>

                                        <a href="views/fichier/3-questionnaire-sante-majeur-2022.pdf" target="_blank"><img src="views/img/medical-history-g6007a00d7_640 (1).png" alt="logo questionnaire sante" width="65px"></a>
                                        <a href="views/fichier/3-questionnaire-sante-majeur-2022.pdf" target="_blank"><h3>Questionnaire sante majeur <i class="fa-solid fa-download"></i></h3></a>
                                        <p>A remplir pour les licenciés actuels si le certificat médical date de moins de 3 ans</p>
                                    </div>
                                    <div class="inscription-cheque">
                                        <h3>Chèque à l'ordre de <strong>"ASMTT"</strong></h3>
                                    </div>
                                    <div class="inscription-ferme">
                                        <a href="#inscription-slide" id="insciption-ferme1">Fermer</a>
                                    </div>
                                    
                                </div>
                            </div>
                        </div>
                        <div>
                            
                            <article class="inscription-ajustement2">
                                <p>SAISON 2022-2023</p>
                            <img src="views/img/ping-pong1.png" alt="logo table ping pong">
                            <h2> Adulte Loisir </h2>
                            <div class="inscription-text">
                                <p>Le mercredi de 19h30 à 21h30.</p>
                                <p>Le vendredi de 19h à 21h.</p>
                            </div>
                            <span class="inscription-plus">+</span>
                            <h2>Entrainement</h2>
                            <h2>Dirigé</h2>
                            <div class="inscription-text">
                                
                                <p>Le mercredi de 20h30 à 21h30.</p>
                                <p class="inscription-petit-text">Avec notre entraineur Dominique (Sauf vacances scolaire)</p>
                            </div> 
                            
                            
                            
                                <h3>150<sup>€</sup></h3>
                                
                                <a href="#inscription-modal2" id="inscription-dossier2">Dossier d'inscription</a>
                            
                            
                            
                            
                        </article>
                        <div class="inscription-modal" id="inscription-modal2">
                            <div class="inscription-container-modal">
                                <h2>Dossier d'inscription Entrainement</h2>
                                <div>

                                    <a href="views/fichier/1-demande-de-licence-2022.pdf" target="_blank"><img src="views/img/1-demande-de-licence-2022-pdf.png" alt="logo formulaire licence" width="65px"></a>
                                    <a href="views/fichier/1-demande-de-licence-2022.pdf" target="_blank"><h3>Licence 2022/2023 <i class="fa-solid fa-download"></i></h3></a>
                                </div>
                                <div>

                                    <a href="views/fichier/2-certificat-medical-2022.pdf" target="_blank"><img src="views/img/logo_certicat_medical.png" alt="logo certificat medical" width="80px"></a>
                                    <a href="views/fichier/2-certificat-medical-2022.pdf" target="_blank"><h3>Certificat medical <i class="fa-solid fa-download"></i></h3></a>
                                    <p>(de moins de 3 mois)</p>
                                    <p>Pour les licenciés actuels, le certificat medical est valide 3 ans à condition de compléter le questionnaire sante</p>
                                </div>
                                <div>

                                    <a href="views/fichier/5-droit-image-2022-2023 (1).pdf" target="_blank"><img src="views/img/camera-g06822f641_640.png" alt="logo camera" width="70px"></a>
                                    <a href="views/fichier/5-droit-image-2022-2023 (1).pdf" target="_blank"><h3>Formulaire de droit a l'image <i class="fa-solid fa-download"></i></h3></a>
                                    <p>Pour les nouveaux adhérents uniquement</p>
                                    <p></p>
                                </div>
                                <div>

                                    <a href="views/fichier/3-questionnaire-sante-majeur-2022.pdf" target="_blank"><img src="views/img/medical-history-g6007a00d7_640 (1).png" alt="logo questionnaire sante" width="65px"></a>
                                    <a href="views/fichier/3-questionnaire-sante-majeur-2022.pdf" target="_blank"><h3>Questionnaire sante majeur <i class="fa-solid fa-download"></i></h3></a>
                                    <p>A remplir pour les licenciés actuels si le certificat médical date de moins de 3 ans</p>
                                </div>
                                <div class="inscription-cheque">
                                    <h3>Chèque à l'ordre de <strong>"ASMTT"</strong></h3>
                                </div>
                                <div class="inscription-ferme">
                                    <a href="#inscription-slide" id="insciption-ferme2">Fermer</a>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                    <div>

                        <article class="inscription-ajustement3">
                            <p>SAISON 2022-2023</p>
                            <img src="views/img/children.png" alt="logo enfant">
                            <h2>Entrainement Jeune</h2>
                            <p>Avec notre entraineur Dominique.</p>
                            <div class="inscription-text">
                                
                                <p>Le mercredi de 19h30 à 20h30.</p>
                                <p>Le vendredi de 19h à 20h30.</p>
                                <p>Pas d'entrainement pendant les petites et grandes vacances mais il est quand même possible de venir s'entrainer avec les adultes</p>
                                
                            </div>
                            <h3>110<sup>€</sup></h3>
                            
                            <a href="#inscription-modal3" id="inscription-dossier3">Dossier d'inscription</a>
                            
                            
                            
                        </article>
                        <div class="inscription-modal" id="inscription-modal3">
                            <div class="inscription-container-modal">
                                <h2>Dossier d'inscription Jeune</h2>
                                <div>

                                    <a href="views/fichier/1-demande-de-licence-2022.pdf" target="_blank"><img src="views/img/1-demande-de-licence-2022-pdf.png" alt="logo formulaire licence" width="65px"></a>
                                    <a href="views/fichier/1-demande-de-licence-2022.pdf" target="_blank"><h3>Licence 2022/2023 <i class="fa-solid fa-download"></i></h3></a>
                                </div>
                                <div>

                                    <a href="views/fichier/5-droit-image-2022-2023 (1).pdf" target="_blank"><img src="views/img/camera-g06822f641_640.png" alt="logo camera" width="70px"></a>
                                    <a href="views/fichier/5-droit-image-2022-2023 (1).pdf" target="_blank"><h3>Formulaire de droit a l'image <i class="fa-solid fa-download"></i></h3></a>
                                    <p>Pour les nouveaux adhérents uniquement</p>
                                </div>
                                <div>
                                    <a href="views/fichier/4-questionnaire-sante-mineur-2022.pdf" target="_blank"><img src="views/img/medical-history-g6007a00d7_640 (1).png" alt="logo questionnaire sante" width="65px"></a>
                                    <a href="views/fichier/4-questionnaire-sante-mineur-2022.pdf" target="_blank"><h3>Questionnaire sante Mineur <i class="fa-solid fa-download"></i></h3></a>
                                </div>
                                <div class="inscription-cheque">
                                    <h3>Chèque à l'ordre de <strong>"ASMTT"</strong></h3>
                                </div>
                                <div class="inscription-img-aide">
                                    <h3>Aides financières</h3>
                                    <div>

                                        <a href="https://www.pass.sports.gouv.fr/" target="_blank"><img src="views/img/passsport-logo.svg" alt="logo Pass sport"></a>
                                        <a href="https://www.auvergnerhonealpes.fr/passregion" target="_blank"><img src="views/img/Logo-bleu-png-2020-pass-region-981x1024.png" alt="logo pass region"></a>
                                        <a href="https://www.ville-mornant.fr/Le-Passeport-Junior-mornant-art-100.html" target="_blank"><img src="views/img/Passeport junior adapté couv 2023-24 Web.jpg" alt="passport junior mornant"></a>
                                    </div>
                                </div>
                                <div class="inscription-ferme">
                                    <a href="#inscription-slide" id="insciption-ferme3">Fermer</a>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                </div>
                </section>




            </main>

           