<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tennis de table AS Mornant</title>
    <link rel="stylesheet" href="views/css/normalize.css">
    <link rel="stylesheet" href="views/css/style.css">
    <!-- slider slick -->
    <link rel="stylesheet" type="text/css" href="views/css/slick.css" />
    <link rel="stylesheet" type="text/css" href="views/css/slick-theme.css" />
    <!-- ------------google font---------------- -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans&display=swap" rel="stylesheet">
    <!-- ------------font awesome---------------- -->
    <script src="https://kit.fontawesome.com/22863556a4.js" crossorigin="anonymous"></script>
    <!-- ------------jQuery---------------- -->
    <script src="https://code.jquery.com/jquery-3.6.4.js"
        integrity="sha256-a9jBBRygX1Bh5lt8GZjXDzyOB+bWve9EiO7tROUtj/E=" crossorigin="anonymous"></script>
    <!-- ------------Js---------------- -->
    
</head>

<body class="clean-transition">
    <!-- <div class="mycanvas" id="mycanvas">
        <div class="trait"></div>
        <div class="filet"></div>
        <div class="filet2"></div>
        <div class="bord2"></div>
       
        <div class="containerloader" id="rotate">
  
            <div class="ball" ></div>
            <div class="ball"></div>
            <div class="ball" id="ball"></div>
            <div class="ball"></div>
            
          </div>
    </div> -->

    <div class="contenu" id="contenu">

    <?php include $template. '.phtml' ?>


    <footer>
                                <div class="footerback"></div>
                                <div class="pied-page">
                                    <div class="logo-mornant">
                                        <img src="views/img/logo-tt-white.png" alt="logo-tt-white">
                                    </div>
                                    <div class="footer-list">
                                        <h3>Nous rejoindre</h3>
                                        <ul>
                                            <li><a href="index.php?action=inscription">Inscription</a></li>
                                            <li><a href="index.php?action=contact">Contact</a></li>
                                            <li><a href="index.php?action=historique">A propos</a></li>
                                        </ul>
                                    </div>
                                    <div class="icon-footer">
                                        <a href="https://www.facebook.com/profile.php?id=100091895204156" target="_blank"><i class="fa-brands fa-square-facebook"></i></a>
                                    </div>
                                    <h3 class="footer-titre-partenaire">Nos partenaires</h3>
                                    <div class="partenaire">
                                        <a href="https://www.ville-mornant.fr/" target="_blank"><img src="views/img/mornantb.png" alt="logo-ville-de-mornant"></a>
                                        <a href="https://www.fftt.com/site/" target="_blank"><img src="views/img/fftt.png" alt="logo-fftt"></a>
                                        <a href="http://www.castanosport.fr/" target="_blank"><img src="views/img/castano.png" alt="logo-castano"></a>
                                        <a href="https://concessions.peugeot.fr/mornant" target="_blank"><img src="views/img/peugeot.png" alt="logo-peugeot"></a>
                                        <a href="http://garage-morellon.fr/" target="_blank"><img src="views/img/citroen.png" alt="logo-citroen"></a>
                                    </div>
                                    
                                    
                                </div>
                                
                            </footer>
                            <!-- <script src="test.js"></script> -->
                            <script src="https://unpkg.com/scrollreveal@4.0.0/dist/scrollreveal.min.js"></script>
                            <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
                            <script src="views/Js/jquery.js"></script>
                            <script src="views/Js/plugin.js"></script>
                            <script src="views/Js/main.js"></script>
                
                </div>

                <script>
                    // ******************************changement d'image background******************************
                    if(window.location.pathname.endsWith('/index.php')){
                        const images = [  'url(views/img/Photo-concours.webp)', 'url(views/img/pexels-magda-ehlers-4080060.webp)', 'url(views/img/homme-pingpong.jpg)'];

                        let currentIndex = 0;
                        const background = document.getElementById('back');

                        setInterval(() => {
                            currentIndex = (currentIndex + 1) % images.length;
                            background.style.backgroundImage = images[currentIndex];
                        }, 10000);
                    }
                </script>
                </body>
                
                </html>